CREATE TABLE  "MEDICAMENTE" 
   (	"ID_MEDICAMENT" NUMBER(*,0) NOT NULL ENABLE, 
	"NUME_MEDICAMENT" VARCHAR2(40) NOT NULL ENABLE, 
	"TIP_MEDICAMENT" VARCHAR2(20) NOT NULL ENABLE, 
	"PRET_MEDICAMENT" NUMBER(7,2) NOT NULL ENABLE, 
	 CONSTRAINT "TIP_MEDICAMENT_CK" CHECK ("TIP_MEDICAMENT" IN('anabolizante','analgezice','vitamine')) ENABLE, 
	 PRIMARY KEY ("ID_MEDICAMENT")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "FARMACIILE_DEPOZITULUI" 
   (	"ID_FARMACIE" NUMBER(*,0) NOT NULL ENABLE, 
	"NUME_FARMACIE" VARCHAR2(40) NOT NULL ENABLE, 
	 CONSTRAINT "FARMACIILE_DEPOZITULUI_PK" PRIMARY KEY ("NUME_FARMACIE")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "COMENZI_DEPOZIT" 
   (	"ID_COMANDA" NUMBER(*,0) NOT NULL ENABLE, 
	"NUME_FARMACIE" VARCHAR2(40) NOT NULL ENABLE, 
	"ID_MEDICAMENT" NUMBER(*,0) NOT NULL ENABLE, 
	"DATA_COMANDA" DATE NOT NULL ENABLE, 
	"SUMA_COMANDA" NUMBER(7,2) NOT NULL ENABLE, 
	 CONSTRAINT "COMENZI_DEPOZIT_PK2" PRIMARY KEY ("ID_MEDICAMENT", "NUME_FARMACIE")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "COMENZI_DEPOZIT" ADD CONSTRAINT "COMENZI_DEPOZIT_FK" FOREIGN KEY ("NUME_FARMACIE")
	  REFERENCES  "FARMACIILE_DEPOZITULUI" ("NUME_FARMACIE") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "COMENZI_DEPOZIT" ADD CONSTRAINT "COMENZI_DEPOZIT_FK2" FOREIGN KEY ("ID_MEDICAMENT")
	  REFERENCES  "MEDICAMENTE" ("ID_MEDICAMENT") ON DELETE CASCADE ENABLE
/
